services:
  db:
    image: postgres:17.5-alpine
    env_file:
      - ${PWD}/docker/db/.postgres.env
    volumes:
      - postgres-data:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres-data:

